# Generated by Django 4.2.3 on 2023-08-08 21:41

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_city",
                to="accounts.city",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default/default.png", upload_to=accounts.models.profile_image
            ),
        ),
    ]
