# Generated by Django 4.2.3 on 2023-08-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("FT", "Full Time"), ("PT", "Part Time")],
                max_length=2,
                null=True,
            ),
        ),
    ]
