# Generated by Django 4.2.3 on 2023-08-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_job_created_at_alter_job_discription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_edit",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
