# Generated by Django 4.2.3 on 2023-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_job_last_edit_alter_job_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="last_edit",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
