# Generated by Django 4.2.3 on 2023-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_alter_job_last_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ex_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="vacancy",
            field=models.IntegerField(default=1),
        ),
    ]
