# Generated by Django 4.2.3 on 2023-08-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_job_ex_years_job_salary_job_vacancy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
    ]
