# Generated by Django 4.2.3 on 2023-08-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0010_category_created_at_category_last_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to="jobs/"),
            preserve_default=False,
        ),
    ]
