# Generated by Django 4.2.3 on 2023-08-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0013_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="job",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apply_job",
                to="job.job",
            ),
            preserve_default=False,
        ),
    ]
